# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title               : Openmined Documentation
author              : The Openmined Community
copyright           : "2022"  # Copyright year to be placed in the footer
logo                : openmined.svg
email               : info@openmined.org
# Short description about the book
description: >-
  A brief introduction to Python programming for scientific applications.
# Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
exclude_patterns     : [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
# Auto-exclude files not in the toc
only_build_toc_files  : true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off

# HTML-specific settings
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon                     : favicon.png
  home_page_in_navbar         : true
  use_multitoc_numbering      : true   # Continuous numbering across parts/chapters
  use_issues_button           : true # Add GitHub buttons to your book
  use_repository_button       : true # Add GitHub buttons to your book
  extra_navbar: |
    <div>
      <section id="adding-a-license-to-your-html-footer">
        <h2>Adding a license to your HTML footer<a class="headerlink" href="#adding-a-license-to-your-html-footer" title="Permalink to this heading">#</a></h2>
        <p>If you’d like to add a more detailed license for your book, or would like to
        add a link to an external page for a license, the easiest way to do so is to
        use a custom footer for this. You can disable the “copyright” text that is
        automatically added to each footer, and add whatever footer HTML you’d like.</p>
        <p>For example, see this configuration:</p>
        <div class="highlight-yaml notranslate"><div class="highlight"><pre id="codecell14"><span></span><span class="nt">html</span><span class="p">:</span>
        <span class="w">  </span><span class="nt">extra_footer</span><span class="p">:</span><span class="w"> </span><span class="p p-Indicator">|</span>
        <span class="w">    </span><span class="no">&lt;p&gt;</span>
        <span class="w">    </span><span class="no">... Add license info here...</span>
        <span class="w">    </span><span class="no">&lt;/p&gt;</span>
        <span class="nt">sphinx</span><span class="p">:</span>
        <span class="w">  </span><span class="nt">config</span><span class="p">:</span>
        <span class="w">    </span><span class="nt">html_show_copyright</span><span class="p">:</span><span class="w"> </span><span class="l l-Scalar l-Scalar-Plain">false</span>
        </pre><button class="copybtn o-tooltip--left" data-tooltip="Copy" data-clipboard-target="#codecell14">
              <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-copy" width="44" height="44" viewBox="0 0 24 24" stroke-width="1.5" stroke="#000000" fill="none" stroke-linecap="round" stroke-linejoin="round">
          <title>Copy to clipboard</title>
          <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
          <rect x="8" y="8" width="12" height="12" rx="2"></rect>
          <path d="M16 8v-2a2 2 0 0 0 -2 -2h-8a2 2 0 0 0 -2 2v8a2 2 0 0 0 2 2h2"></path>
        </svg>
            </button></div>
        </div>
        <p>Note that this may not work in PDF builds of your page generated by LaTeX.</p>
      </section>
    </div>
  extra_footer: |
    <div id="footer-links">
      <div class="container-wrapper">
        <div class="container">
          <div class="row">
            <div class="footer-container column small-12 xlarge-10 xlarge-offset-1">
              <ul class="footer-items">
                <li class="logo">
                  <a href="/"><img src="/_static/image/openmined.svg" alt="OpenMined" /></a>
                </li>
                <li><a href="https://blog.openmined.org" target="_blank" rel="noopener noreferrer">Blog</a></li>
                <li><a href="https://store.openmined.org" target="_blank" rel="noopener noreferrer">Store</a></li>
                <li><a href="/_static/pdf/openmined-brand-guide.pdf" target="_blank" rel="noopener noreferrer">Brand Guide</a></li>
              </ul>
              <ul class="social-media">
                <li>
                  <a href="https://github.com/OpenMined" target="_blank" rel="noopener noreferrer"><img class="icon" src="/_static/image/github.svg" alt="github" /></a>
                </li>
                <li>
                  <a href="https://twitter.com/openminedorg" target="_blank" rel="noopener noreferrer"><img class="icon" src="/_static/image/twitter.svg" alt="twitter" /></a>
                </li>
                <li>
                  <a href="https://www.youtube.com/c/OpenMinedOrg" target="_blank" rel="noopener noreferrer"><img class="icon" src="/_static/image/youtube.svg" alt="youtube" /></a>
                </li>
                <li>
                  <a href="https://www.facebook.com/openminedorg/" target="_blank" rel="noopener noreferrer"><img class="icon" src="/_static/image/facebook.svg" alt="facebook" /></a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  announcement                : "This documentation page is in test mode." # A banner announcement at the top of the site.

# disable the “copyright” text that is automatically added to each footer
sphinx:
  config:
    html_show_copyright: false
    # html_theme_options:
      # extra_navbar: <h2>This documentation page is in test mode.</h2>
      # extra_footer: <h3>This documentation page is in test mode.</h3>

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : classic  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : ""  # The URL of the BinderHub (e.g., https://mybinder.org)
  jupyterhub_url            : ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  thebe                     : false  # Add a thebe button to pages (requires the repository to run on Binder)
  colab_url                 : "" # The URL of Google Colab (https://colab.research.google.com)
  
# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/callezenwaka/syftbook  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)
