name: syft-example
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.*
  - jupyter
  - sphinx=2.4.4
  - pydata-sphinx-theme
  - ghp-import
  - matplotlib
  - numpy
  - scipy
  - syft
  - sympy
  - pandas
  - networkx
  - numba
  - pip
  - pip:
    - jupyter-book
